### ISSUE TITLE
Dropdown/select box "selected" attribute isn't acknowledged

### ISSUE THREAD

**Issue by bridgeport** [geminilabs/float-labels.js#16]
First off, thanks for putting together this script.

Unlike inputs and textareas, if a select box has a **predefined/initial** `selected="selected"` option, float-labels doesn't activate for that field.

For example, the following will show "United States" styled as a a grayed out placeholder without any floating label:

```
<label for="country">Country</label>
<select id="country">
    <option>Country</option>
    <option value="CA">Canada</option>
    <option value="US" selected>United States</option>
</select>
```

**Comment by pryley** [comment]
I am only able to reproduce this issue when a form is reset, is this also true for you?

If it is not isolated to the form reset event in your project, then it could also be due to a conflict. If this is the case, you may want to download and edit the `index.html` file directly in the repository, then add the example field to the form and test it.
